# Generated by Django 2.1 on 2022-09-08 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='vote_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votes',
            name='vote_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
