# Generated by Django 2.1 on 2023-08-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0006_specialmentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmentions',
            name='special_mentions',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
